### ISSUE TITLE
how to use custom (non-angular) coffee script files

### ISSUE THREAD

**Issue by abbood** [scotch/angular-brunch-seed#107]
i'm migrating over code, and i have several custom made coffeescript files (ie that aren't part of the angular framework).. take a look at an [example](https://gist.github.com/abbood/a5597fcd11aa4dd9937c) here. 

If i put this file under the app/scripts folder.. I immediately get an error at the top: Uncaught syntaxError: illegal return statement.

how do i make it run? or does all my javasctript/coffeescript have to be part of the angular framework?

**Comment by kylefinley** [comment]
@abbood,

Is the error giving you a line number? Adding coffeescript shouldn't be an issue. I would try removing the last return, thought, that might be the issue.

**Comment by abbood** [comment]
yeah that works thanks!
