### ISSUE TITLE
Testacular install error

### ISSUE THREAD

**Issue by JasonSwindle** [scotch/angular-brunch-seed#19]
Howdy,

When trying to install, I get:

npm http 200 https://registry.npmjs.org/testacular

npm ERR! Error: No compatible version found: testacular@'>=0.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17"]
npm ERR!     at installTargetsError (/usr/lib/nodejs/npm/lib/cache.js:486:10)
npm ERR!     at next_ (/usr/lib/nodejs/npm/lib/cache.js:436:17)
npm ERR!     at next (/usr/lib/nodejs/npm/lib/cache.js:413:44)
npm ERR!     at /usr/lib/nodejs/npm/lib/cache.js:406:5
npm ERR!     at saved (/usr/lib/nodejs/npm/lib/utils/npm-registry-client/get.js:151:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 2.6.32-279.5.2.el6.x86_64
npm ERR! command "nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/nodejs/playground/jason/brunch/gsc
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.19
npm ERR! message No compatible version found: testacular@'>=0.2.0'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/nodejs/playground/jason/brunch/gsc/npm-debug.log
npm not ok

**Comment by kylefinley** [comment]
Hi Jason, 

That's strange, Testacular 0.2.0 is the [latest version](https://npmjs.org/package/testacular).  I just tested `./scripts/init.sh` on my system and it worked, so maybe this is an npm caching issue on your system. Try:

```
npm cache clean
./scripts/init.sh
```

If that doesn't work, let me know, so I can try to think of what else might be causing this.

Thanks,

Kyle

**Comment by JasonSwindle** [comment]
Howdy Sir, 

I tried the above step, and still the same error:

---

npm ERR! Error: No compatible version found: testacular@'>=0.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17"]
npm ERR!     at installTargetsError (/usr/lib/nodejs/npm/lib/cache.js:486:10)
npm ERR!     at next_ (/usr/lib/nodejs/npm/lib/cache.js:436:17)
npm ERR!     at next (/usr/lib/nodejs/npm/lib/cache.js:413:44)
npm ERR!     at /usr/lib/nodejs/npm/lib/cache.js:406:5
npm ERR!     at saved (/usr/lib/nodejs/npm/lib/utils/npm-registry-client/get.js:151:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 2.6.32-279.5.2.el6.x86_64
npm ERR! command "nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/nodejs/playground/jason/brunch/gsc/scripts
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.19
npm ERR! message No compatible version found: testacular@'>=0.2.0'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/nodejs/playground/jason/brunch/gsc/scripts/npm-debug.log

---

My system information:
CentOS release 6.3 (Final)
NodeJS v0.6.18
npm@1.1.19

Thank you for your help. :)

**Comment by kylefinley** [comment]
Ah, i think that your NodeJS version is the problem. Testacular 0.2.0 [requires Node >= 0.8.4](https://github.com/vojtajina/testacular/blob/stable/package.json#L53). So if you want to use testacular you will have to updated node. When I have some time I'll add a note to the docs.

Thank you for bringing this to my attention.

**Comment by JasonSwindle** [comment]
Updated, and it now works!  Thank you for the update, and now this Noob can start hacking away.
