### ISSUE TITLE
New Projects can't load JS files.

### ISSUE THREAD

**Issue by Hoverbear** [scotch/angular-brunch-seed#34]
Hi,
Looks like a newly initialized project can't properly run.
Replicate:

```
brunch new myapp --skeleton https://github.com/scotch/angular-brunch-seed
cd myapp
./scripts/server.sh
```

Observe the 'Welcome' page utterly not working.

Looks like when it tried to load vendor.js and app.js they're just html pages (which obviously doesn't work)

**Comment by kylefinley** [comment]
Just to confirm:

Does it work after you refresh the page? I've noticed that on the initial page load, brunch will not capture the `vendor.js` and `app.js` files, but on subsequent loads they will be handled properly. I'll add something to the README about this.

**Comment by Hoverbear** [comment]
You're right, that seems to be the case. Looks great.
