### ISSUE TITLE
How do I set coffeelint options

### ISSUE THREAD

**Issue by gduquesnay** [scotch/angular-brunch-seed#38]
I'd like to change some of the coffeelint options but not sure how.
I found node_modules/coffeelint-brunch/node_modules/coffeelint/examples/coffeelint.json but I don't know where to put it for brunch to pick it up.

**Comment by kylefinley** [comment]
Does adding adding a `coffeelint`attribute to the `config` object work? E.g.

`config.coffee`

``` coffeescript
export.config =
  # ... previous config
  coffeelint:
    pattern: /^app\/.*\.coffee$/
    options:
      no_trailing_semicolons:
        level: "ignore"
```
- [coffeelint-brunch](https://github.com/ilkosta/coffeelint-brunch)
- [coffeelint options](http://www.coffeelint.org/#options)

**Comment by gduquesnay** [comment]
Thanks.   That works.  It was actually one of the things I tried except that I was setting level to "warn".  I probably just didn't notice that the error message changes slightly to say:

09 Jan 10:13:25 - error: Linting of 'app/scripts/oauth_config.coffee' failed. **warn**: max_line_length at line 47.
(emphasis mine)

I am trying to change it so that max_line_length errors doen't stop the build.  But it seems that "warn"ings still cause brunch to stop.

```
 coffeelint:    pattern: /^app\/.*\.coffee$/
    options:
      max_line_length:
        value: 80
        level: "warn"
```

Any ideas?  Maybe this question belongs in a separate issue.  Please advise.

**Comment by kylefinley** [comment]
If you don't care about the max line length, maybe you could set `level: "ignore"`. Or you could setting it to a high number E.g. `value: 1000`

**Comment by kylefinley** [comment]
I"m going to close this for now. Feel free to reopen if you still have questions

**Comment by aleks-sidorenko** [comment]
Could anyone help me with coffeelint?
I am using this seed, I have added     "coffeelint-brunch": "~1.5.0" to package.json and done npm install (package installed).
But when I run brunch build it doesn't errors/warn me on anything in any case.
What have I missed?
It would be nice to add coffeelint to this seed to have it out of the box!
Thanks
