### ISSUE TITLE
Auto-reload doesn't seem to be triggering

### ISSUE THREAD

**Issue by ttrutna** [scotch/angular-brunch-seed#51]
On a newly checked out copy on OS X 10.7.5 (tested Chrome and Safari) saving changes to files does not cause the browser window to automatically reload.

I'll try to take a deeper look tomorrow to give more details if I'm able.

**Comment by kylefinley** [comment]
@ttrutna, thank you for reporting this.

It looks like the [auto-reload.js](https://github.com/brunch/auto-reload-brunch/blob/master/vendor/auto-reload.js) script isn't being included in `vendor.js`. I'll investigate this further, but It might be a few days before I can get to it.

**Comment by legomind** [comment]
I am also having the issue. Copy auto-reload.js into your app/assets/js folder for now

**Comment by kylefinley** [comment]
Thanks for the tip @legomind. It seems there's an open issue for this:

brunch/auto-reload-brunch/issues/16

I'll keep this issue open until it's resolved.

**Comment by paulmillr** [comment]
fixed?

**Comment by legomind** [comment]
Yes. Latest commit working for me.

**Comment by kylefinley** [comment]
@legomind did you make any modifications angular-brunch-seed to make this work?

I've updated to the lastest brunch and removed `auto-reload.js` from `app/assets/js`, but brunch isn't compiling the contents of `auto-reload.js` into `vendor.js` for me. 

If you have `angular-brunch-seed` in a working state would you mind sending a pull request?

Thanks,

Kyle
