### ISSUE TITLE
./scripts/production.sh doesn't run

### ISSUE THREAD

**Issue by ttrutna** [scotch/angular-brunch-seed#52]
This isn't blocking my workflow but thought I'd mention it (until I get a chance to investigate myself). 

<pre>
$> ./scripts/production.sh 
'-m' expects a value

Usage: brunch build [options]

Options:
  -v, --version               display brunch version
  -c CONFIG, --config CONFIG  path to config file
  -o, --optimize              optimize result files (minify etc.)

Description:
  Build a brunch project
</pre>

**Comment by kylefinley** [comment]
@ttrutna , Fixed now, thanks for reporting this.
