### ISSUE TITLE
Responsive bootstrap broken

### ISSUE THREAD

**Issue by cdcme** [scotch/angular-brunch-seed#60]
Tested default To Do app at 1280x1024 and 1024x768.

**Comment by kylefinley** [comment]
Hey @carlodicelico,

Would you mind explaining this a little more? Could you provide a screen shot?

When I resize the browsers the layout seems to be adjusting. What are you seeing? Is this a Bootstrap issue or a angular-brunch-seed issue?

Thanks,

Kyle

**Comment by cdcme** [comment]
This ended up being an issue caused by a browser plugin that I have installed. Closing it.
