### ISSUE TITLE
Integration of AngularStrap

### ISSUE THREAD

**Issue by christianarielli** [scotch/angular-brunch-seed#61]
Hi!

Anybody out there who can help me integrating AngularStrap (https://github.com/mgcrea/angular-strap)?

I added angular-strap to `component.json` and did a `bower install`

``` coffeescript
{
  "name": "bower-brunch",
  "version": "0.0.1",
  "main": [],
  "dependencies": {
    "console-polyfill": "*",

    "jquery": "1.8.3",

    "bootstrap": "2.3.1",
    "bootstrap-less-themes": "git://github.com/scotch/bootstrap-less-themes.git",
    "font-awesome": "3.0.2",

    "angular": "1.0.4",
    "angular-sanitize": "1.0.4",
    "angular-resource": "1.0.4",
    "angular-cookies": "1.0.4",
    "angular-mocks": "git://github.com/fabsor/bower-angular-mocks.git#v1.0.4",
    "angular-strap": "git://github.com/mgcrea/angular-strap.git"
  }
}
```

Now angular-strap appears as an subdirectory of the vendor directory. But, what else do I need to get it up and running? Until now it seems that the .js and .css files won't be integrated automatically?

Much thanks in advance!

Regards,
Christian

**Comment by kylefinley** [comment]
@christianjunk ,

Sorry for the late response. 

You'll have to specify the location of the files  in `config.coffee` (Sorry,  I need documentation on this)

https://github.com/scotch/angular-brunch-seed/blob/master/config.coffee#L47

I think for angular-strap it would something like this:

``` coffeescript
    # ...
    bower:
      extend:
        "bootstrap" : 'vendor/bootstrap/docs/assets/js/bootstrap.js'
        "angular-mocks": []
        "styles": []
        "angular-strap" : 'vendor/bootstrap/angular-strap/dist/angular-strap.js'
      asserts:
        "img" : /bootstrap(\\|\/)img/
        "font": /font-awesome(\\|\/)font/
```

`extends` is for javascript and `asserts` (should be `assets` will be changed in the future) is for assets, E.g. image fonts. Hopefully in the future this will not be necessary. 

Please let me know it that works.

**Comment by christianarielli** [comment]
@kylefinley Thank you for your response. I added the lines to my configuration and now it works. Thank you! Regards, Christian
