### ISSUE TITLE
Bootstrap versions don't match

### ISSUE THREAD

**Issue by sanfordredlich** [scotch/angular-brunch-seed#72]
Hi, thanks for a great project.

When I run "bower install" I get:

...
Please note that
    angular-brunch-seed requires bootstrap 2.2.2
    bootstrap-less-themes requires bootstrap ~2.3.1
...

Should be pretty easy to resolve, should angular-brunch-seed be moved to a newer bootstrap?

Thanks,
- S.

**Comment by kylefinley** [comment]
@sanfordredlich, thanks for reporting this.

I bumped the version number. Please let me know if you're still seeing the warning.

**Comment by sanfordredlich** [comment]
Perfect, fixed. Now that's rapid response.
