### ISSUE TITLE
Created a "modularized" fork some people might find useful

### ISSUE THREAD

**Issue by sanfordredlich** [scotch/angular-brunch-seed#74]
Thanks for creating this very useful starter setup!

I was inspired to make a modified version in a fork, to make it modularized to better match Misko's comments on best practices for organizing Angular code. This makes more complicated but possibly a better template to build a bigger app from.

In case you'd like to add it to the "forks" list in the README:
https://github.com/sanfordredlich/angular-brunch-seed-modularized

Why do this? My added notes to the README:

Angular-brunch-seed is awesome, a great start for making Angular apps. I wanted this "modularized" version because Misko recommends organizing code around features rather than type of code, like controllers.coffeee, etc. (see this 10/27/13 presentation: http://www.youtube.com/watch?feature=player_embedded&v=E87rXWE62WU#t=106s).

That is, organize your modules by feature. Instead of one big module, have one module per feature (or page). This is better now for

unit testing
working with larger teams (to not step on each others’ work)
preparing for the future because modules will be able to be lazy-loaded and so this structure will be either required or firmly recommended
These are the files that changed:

```
# modified:   app/app.coffee
# modified:   app/index.jade
# modified:   app/scripts/controllers.coffee
# modified:   test/karma.conf.js
# modified:   test/unit/contoller.spec.coffee
#
# added:
# app/sections/
# test/unit/sections/
```

Thanks again for making angular-brunch-seed, cheers,  
- Sanford

**Comment by kylefinley** [comment]
Hey @sanfordredlich nice work! I _do_ like the idea of breaking the app into logical sections. I experimented with idea, to some extent, in [sapling](https://github.com/scotch/sapling/tree/master/app/scripts). I definitely think that your on the right track; it will be interesting to see how things develop in the upcoming release of [Angular2 with the incorporation of web components](https://groups.google.com/d/msg/polymer-dev/4RSYaKmbtEk/uYnY3900wpIJ).

I added angular-brunch-seed-modularized to the README If you prefer a different descriptions please send me a pull request I'll get it changed.

**Comment by sanfordredlich** [comment]
Looks great @kylefinley, thanks!
