### ISSUE TITLE
Add Peer Dependencies to package.json

### ISSUE THREAD

**Issue by kylefinley** [scotch/angular-brunch-seed#79]
Once Brunch 1.7.0 is released, add peer dependencies.
Reevaluate issue #13 - Brunch as a dependency 

http://blog.nodejs.org/2013/02/07/peer-dependencies/

https://github.com/brunch/brunch/issues/628

**Comment by es128** [comment]
You can probably close this. Turns out the original idea won't work for skeletons.

On the bright side, brunch as a dependency will now become a more standard design pattern with https://github.com/brunch/brunch/pull/634

**Comment by kylefinley** [comment]
Oh, OK, thanks Elan.
