### ISSUE TITLE
css files from main property are not included to app.css by default

### ISSUE THREAD

**Issue by fijolekProjects** [scotch/angular-brunch-seed#84]
Like title says. I had to add <code>bower_components</code> in <code>config.coffee</code> in <code>joinTo</code> section to include css files to my <code>app.css</code>.

**Comment by kylefinley** [comment]
Which bower package where you having problems with?

Brunch uses the `.bower.json` file's `main` attribute to determine which css / js files to load [example](https://github.com/twbs/bootstrap/blob/3.0.0-wip/bower.json#L4). If the package you are attempting to use does not have a `main attribute you can add it manually. [here's a bad example](https://github.com/scotch/angular-brunch-seed/blob/master/bower.json#L30), but shows the concept

**Comment by fijolekProjects** [comment]
Writing "main property" I meant main property from <code>bower.json</code>. I'm aware of override feature, but still css files are not included to project. I had to add <code>bower_component</code> in <code>config.coffee</code> like this:

<pre><code>stylesheets:
      joinTo:
        'css/app.css': /^(app|vendor|bower_components)/</code></pre>

**Comment by kylefinley** [comment]
Ah, I hadn't' run into this yet. Thanks for the fix @fijolekProjects

**Comment by fijolekProjects** [comment]
You're welcome. Keep this project up!
