### ISSUE TITLE
Modules?

### ISSUE THREAD

**Issue by sanfordredlich** [scotch/angular-brunch-seed#86]
Hi Kyle,

I was just about to update my "modularized" branch (intended to give a better guide to creating larger apps) to get your latest updates when I thought I'd ask: would you like me to instead just give you a pull request of the changes and modularize angular-brunch-seed itself? I think you mentioned you wanted to do that. Just let me know, the differences I could make are below.

Differences

Instead of one controller, one partials folder, one module, there are several
top level ones under /app
lower-level ones under /app/sections
(to make that work, karma.conf.js and config.coffee had to be changed, to pick up and integrate the files from more locations)

Instead of using the $routeProvider, it uses angular-ui-router to allow output to multiple named views, nested views, etc. Routing and ng-view was mentioned by many online as pain points for larger apps. This arrangement should be much better.

Thanks,
- Sanford

**Comment by kylefinley** [comment]
Hey Sanford,

Yeah, lets do it! My only concern is switching folks to `angular-ui-router`, but I think it's considered best practices as this point, so we'll see how it goes.

Thanks for your contributions, I really appreciate them.

Kyle

**Comment by sanfordredlich** [comment]
Cool, I'll give it a go. More soon,  - S.

**Comment by sanfordredlich** [comment]
The pull request is filed, closing...
