### ISSUE TITLE
E2E tests failing

### ISSUE THREAD

**Issue by sanfordredlich** [scotch/angular-brunch-seed#87]
commands entered on the command line:

brunch new https://github.com/scotch/angular-brunch-seed.git as2
cd as2
bower install
./scripts/test-e2e.sh 

console output:

WARN [config]: config.configure() is deprecated, please use config.set() instead.
INFO [karma]: Karma v0.9.8 server started at http://localhost:9876/__karma/
INFO [launcher]: Starting browser Chrome
WARN [watcher]: Pattern "/Users/sanfordredlich/Documents/git/as2/test/e2e/*_/_.js" does not match any file.
INFO [Chrome 28.0.1500 (Mac OS X 10.8.4)]: Connected on socket id C6tU6puaTccSnqgLEO_Y
WARN [proxy]: failed to proxy / ([object Object])

browser shows frozen tests

Any ideas?

**Comment by kylefinley** [comment]
I'm not sure. I updated Karma v0.9.8 and the tests are still passing.

**Comment by sanfordredlich** [comment]
You mean the e2e tests work for you? Hmmm...

On my fresh install, "npm show karma version" gives me "0.10.1"

**Comment by kylefinley** [comment]
Do you have the server running? Some times I forget to start up the server (`./script/server.sh`) and the test will freeze on the first one.

> You mean the e2e tests work for you?

Yes, this is what I'm seeing with v`0.10.1` when I click the **DEBUG** button:
![screen shot 2013-08-08 at 10 43 51 pm](https://f.cloud.github.com/assets/756228/936234/0ef5dbd0-00a6-11e3-8105-aaef58b22710.png)

**ps** I wouldn't think that it would matter, but `./scripts/test-e2e.sh` uses the local karma i.e. `node_modules/.bin/karma` so the version might be different.

**Comment by sanfordredlich** [comment]
Ah, you're right, sorry. I thought the e2e tests were running via PhantomJS. I guess I'd always accidentally had the server running. Closing...
