### ISSUE TITLE
components folder not picked up by config.coffee

### ISSUE THREAD

**Issue by chartotu19** [scotch/angular-brunch-seed#90]
I forked angular-brunch-seed package ~6 months ago when there was no bower support. I now manually installed bower but the config compiler is not picking up the components folder.
I changed this line 
        'js/vendor.js': /^vendor/
to 
        'js/vendor.js': /^(vendor|components)/

**Comment by kylefinley** [comment]
I'm not sure what the problem would be. Have you updated your Bruch  and Bruch plugins?
https://github.com/scotch/angular-brunch-seed/blob/master/package.json#L15

**Comment by chartotu19** [comment]
The [dependencies](https://github.com/SOCRedu/SOCR-framework/blob/dev/package.json#L18) seems to be fine except for bower which I manually installed. My issue is how to make brunch pick up another folder along with vendor? I make this change in config.coffee.
'js/vendor.js': /^(vendor|ANOTHER_FOLDER)/

This doesnt seem to work. Any leads/direction where I should look?

Thanks

**Comment by kylefinley** [comment]
Try upgrading your Brunch to `~1.7`. That's when bower support was added. You probably want to update the other Brunch package too.

https://github.com/scotch/angular-brunch-seed/blob/master/package.json#L18

**Comment by chartotu19** [comment]
I will do that first. Thanks!
